<div class="mail-content-wrap" style="height: 900px;">
<center>
<h2>Chatting with <?php echo $this->studentname ?></h2>
</center>
<div class="mail-block"  style="background-color: white">
﻿<div id="chat" person="teacher" personid="1" otherpersonid="<?php echo $this->stid ?>"></div>
<div id="chatbox"></div>
</div><br/>
<input type="button" id="smile01" style="background-image : url(/i/smiles/cool.gif);" smilecode="[:cool:]" class ="smilebuttons" alt="cool"/>
<input type="button" id="smile02" style="background-image : url(/i/smiles/dont.gif);" smilecode="[:dont:]" class ="smilebuttons" alt="dont"/>
<input type="button" id="smile03" style="background-image : url(/i/smiles/evil.gif);" smilecode="[:evil:]" class ="smilebuttons" alt="evil"/>
<input type="button" id="smile04" style="background-image : url(/i/smiles/good.gif);" smilecode="[:good:]" class ="smilebuttons" alt="good"/>
<input type="button" id="smile05" style="background-image : url(/i/smiles/love.gif);" smilecode="[:love:]" class ="smilebuttons" alt="love"/>
<input type="button" id="smile06" style="background-image : url(/i/smiles/sad.gif);" smilecode="[:sad:]" class ="smilebuttons" alt="sad"/>
<input type="button" id="smile07" style="background-image : url(/i/smiles/saint.gif);" smilecode="[:saint:]" class ="smilebuttons" alt="saint"/>
<input type="button" id="smile08" style="background-image : url(/i/smiles/scared.gif);" smilecode="[:scared:]" class ="smilebuttons" alt="scared"/>
<input type="button" id="smile09" style="background-image : url(/i/smiles/suspend.gif);" smilecode="[:suspend:]" class ="smilebuttons" alt="suspend"/>
<input type="button" id="smile10" style="background-image : url(/i/smiles/ugly.gif);" smilecode="[:ugly:]" class ="smilebuttons" alt="ugly"/>
<input type="button" id="smile11" style="background-image : url(/i/smiles/music.gif);" smilecode="[:music:]" class ="smilebuttons" alt="music"/>
<input type="button" id="smile11" style="background-image : url(/i/smiles/lucky.gif);" smilecode="[:lucky:]" class ="smilebuttons" alt="lucky"/>
<input type="button" id="smile12" style="background-image : url(/i/smiles/wink.gif);" smilecode="[:wink:]" class ="smilebuttons" alt="wink"/><br/>
<div style="width:395px; background-color: #fff">
<textarea id="chatinput" name="chatinput" onkeypress="handleKeyPress(event)" cols="14" rows="1" style="width:395px; background-color: #fff"></textarea>
</div><br/>
<input type="button" id="chatsubmit" value="לשלוח"/>
</div>