<div class="mail-content-wrap" id="chat" person="teacher" personid="1" isvisible="<?php echo $this->visibility ?>" style="height: 800px;">
    <div id="invisiblemode">
        <div id="invisiblestatus">
            <?php if ($this->visibility): ?>
                <b style='color:Green'>Visible</b>
            <?php else: ?>
                <b style='color:red'>Invisible</b>                
            <?php endif; ?>
        </div>
        <a href="#" class="changevisibility" setvisibility="1"><img src="/i/teacheronline.png" alt="Visible"/></a>
        <a href="#" class="changevisibility" setvisibility="0"><img src="/i/teacheroffline.png" alt="Invisible"/></a>
    </div><br/>
<?php if (!$this->allstudents) :?>
    <h2>No Students registered</h2>
<?php else: ?>
    <table id="allstudentstable">
    <?php $i=2 ?>
    <?php foreach ($this->allstudents as $student): ?>
        <?php if (($i++)%2==0): ?>
            <tr>
        <?php endif;?>
                <td>
                 <?php if (!isset ($student['u_picture'])): ?>
                    <a href="/teacher/dashboard/view-student/stid/<?php echo $student['u_id']?>"><img src="/i/noava.gif" class="avatarbox" alt="ava"></a>
                  <?php else: ?>
                    <a href="/teacher/dashboard/view-student/stid/<?php echo $student['u_id']?>"><img src="<?php echo "/avatars/".$student['u_picture']?>" class="avatarbox" alt="ava"></a>
                  <?php endif; ?>
                </td>
            <td class="databox">
                  <?php echo $student['u_family_name']; ?>&nbsp;<?php echo $student['u_name']; ?> (<?php echo strtolower($student['u_ip_country']) ?>)<br/>
                  <a href='mailto:<?php echo $student['u_email']?>'><?php echo $student['u_email']?></a><br/>
                  <?php if (in_array($student['u_id'], $this->allonlinestudents)): ?>
                    <span style="color: green">online<a href="/teacher/dashboard/chat/stid/<?php echo $student['u_id']?>" target="new"><img alt="start chat" src="/i/chat.png"/></a></span>
                    <?php else: ?>
                    <span style="color: red">offline<a href="/teacher/dashboard/chat/stid/<?php echo $student['u_id']?>" target="new"><img alt="start chat" src="/i/chat.png"/></a></span>
                  <?php endif ?>
            </td>
        <?php if (($i%2)==0): ?>
            </tr>
        <?php endif;?>
    <?php endforeach;?>
     </table>
    <div id="paginator">
        <?php for ($i=1;$i<=$this->numpages;$i++): ?>
            <?php if ($this->currentpage==$i): ?>
            <b><?php echo $i ?></b>
            <?php else: ?>
            <a href = "/teacher/dashboard/index/page/<?php echo $i?>"><?php echo $i; ?></a>
            <?php endif; ?>
        <?php endfor; ?>
<?php endif; ?>
    </div>
    <br><br>
    <?php if($this->offlinemessages): ?>
    <h3>You've received following messages when you were offline</h3><br/>
    <div>
        <table id="offlinemessagestable">
        <?php foreach($this->offlinemessages as $offlinemessage): ?>
            <tr>
                <td><?php echo $offlinemessage['chat_message'] ?></td>
                <td>&nbsp;</td>
                <td>[<?php echo $offlinemessage['u_family_name']?>]</td>
                <td><a href="/teacher/dashboard/chat/stid/<?php echo $offlinemessage['chat_from_user_id']?>"></a>
                  <?php if (in_array($offlinemessage['chat_from_user_id'], $this->allonlinestudents)): ?>
                    <span style="color: green">online<a href="/teacher/dashboard/chat/stid/<?php echo $offlinemessage['chat_from_user_id']?>" target="new"><img alt="start chat" src="/i/chat.png"/></a></span>
                    <?php else: ?>
                    <span style="color: red">offline<a href="/teacher/dashboard/chat/stid/<?php echo $offlinemessage['chat_from_user_id']?>" target="new"><img alt="start chat" src="/i/chat.png"/></a></span>
                  <?php endif ?>

                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
    <?php endif;?>
</div>
