
            <div class="side_block">
                <div class="sub">
                    <div class="sub-left">

                        <a href="#"><img src="/i/r_button.png"></a>
                        כניסה לחשבון
                    </div>
                    <div class="sub-right">
                        <a href="#"><img src="/i/cat.gif"></a>
                        שלום תותי
                    </div>
                </div>
                <div class="sub-text">
                    .זהו ביקורך ה- 18 במרכז הלמידה
                    <br/>

                    .עד כה צברת 35 שעות תרגול
                    <br/>
                    יש לך 2 הודעות חדשות בתיבת הדואר
                    <br/>
                    עד כה צברת 46 בונוסים
                    <br/><br/>
                </div>
                <div class="sub-block-border1">

                </div>
                <div class="sub-block1">

                    <div class="content-block">

                        שוחחו עם מדריך אונליין
                    </div>
                    <div class="sub-sub-block1">
                        <div class="header">
                        </div>
                        <div class="content">

                        </div>

                        <div class="footer">
                        </div>

                    </div>
                </div>

                <div class="sub-block-border2">

                </div>
                <div class="sub-block2">

                    <div class="sub-sub-block2">
                    </div>
                    <div class="content-block">
                        <div class="sub-header">
                            משוב על התרגול
                        </div>
                        <br/>
                        <strong>האם חווית שיפור או הקלה</strong><br/>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <strong>האם התרגול היה:</strong><br/>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>


                    </div>

                </div>
                <div class="sub-block-border3">
                    <div class="sub-top">
                        <div class="sub-top-content">

                            ?האם חווית בעיה בתרגול
                            <br/> <textarea class="sub_textarea"></textarea><br/>
                            האם יש לך הצעות לשיפור
                            <br/>

                            <input type="text" class="sub_text_input" value="" text="" name="">
                        </div>
                    </div>
                    <div class="sub-bottom">

                        <input type="button" class="sub_button_input" value="שלחו" text="" name="">
                    </div>
                    <div class="sub-bottom-border" id="sub-bottom-border">

                        <div class="sub-bottom-border-block">
                            <div class="sub-bottom-top"></div>
                            <div class="sub-bottom-body">

                                <div class="sub-bot-content">

                                    <strong>מאמר השבוע</strong><br><br>
                                    “על הקשר בין נחיריים לאישיות” <br>
                                    לקריאת המאמר <br><br>
                                    <strong>מונח השבוע</strong><br><br>
                                    <a href="/">טאפאס - חום . קיראו עוד</a>
                                </div>


                            </div>
                            <div class="sub-bottom-bottom"></div>
                        </div>

                        <div class="sub-view-image">
                        <div class="input-title">
                            להצטרפות לקורס הכניסו אימייל
                        </div>
                            <input type="text" class="" value="" text="" name="">

                        </div>

                        <div class="bottom-shape"><div class="text-bottom-shape">
שלחו >
                            </div></div>

<div class="bottom-shape-like"></div>

                    </div>
                </div>


            </div>


            <div class="form_wrap">


                <video id="vid1" width="689" height="579"
                       poster="http://cdn.kaltura.org/apis/html5lib/kplayer-examples/media/bbb480.jpg"
                       durationHint="33"
                        >
                    <source src="http://cdn.kaltura.org/apis/html5lib/kplayer-examples/media/bbb_trailer_400p.ogv"
                            type="video/ogg"/>
                </video>

                <div class="mail-content-wrap">

                    <div class="mail-block-title">

הודעות ממרכז הלמידה
                    </div>
                    <div class="mail-block">

                        <div class="mail-top">

                        </div>

                        <div class="mail-bottom">
                            <div class="mail-bottom-header">

                            </div>

                            <div class="mail-message">

                            </div>


                        </div>
                    </div>




                </div>



                <div class='video_link'>
                    <iframe title="YouTube video player" width="623" height="686"
                            src="http://www.youtube.com/embed/ew9KuRkTt_Y" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
                 <div class="for_ie">

                </div>
