<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <title>אימות סיסמא</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
    <!--[if gt IE 7]><!-->
    <link rel="stylesheet" media="screen" type="text/css" href="/styles/main_std.css">

    <!--<![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <link rel=stylesheet media="screen" type="text/css" href="/styles/ie.css"/>

    <script type="text/javascript" src="/js/ie.js"></script>
    <![endif]-->

     <!--[if IE]>
        <link rel=stylesheet media="screen" type="text/css" href="/styles/cross/ie.css"/>
    <![endif]-->

    <!--[if opera 11]>
    <link rel=stylesheet media="screen" type="text/css" href="/styles/cross/op.css"/>
    <![endif]-->

    <script type="text/javascript" src="/js/kultura/jquery-1.4.2.min.js"></script>

    <!-- Include Kultura -->
    <!-- Debug version: If using the debug version you can remove all the below js / css references -->
    <!--  <script type="text/javascript" src="/js/kultura/mwEmbed.js" ></script>  -->

    <style type="text/css">
        @import url("/js/kultura/skins/jquery.ui.themes/kaltura-dark/jquery-ui-1.7.2.css");
    </style>
    <style type="text/css">
        @import url("/js/kultura/mwEmbed-player-static.css");
    </style>
    <script type="text/javascript" src="/js/kultura/mwEmbed-player-static.js"></script>


</head>
<body class="main_page">
<div class="wrapper">
    <section class="base">
        <div class="content_row">
            <!--<header>
                   <h1 class="headline">הרשמה</h1>
               </header>-->

            <div class="side_block">
                <div class="sub">
                    <div class="sub-left">

                        <a href="#"><img src="/i/r_button.png"></a>
                        כניסה לחשבון
                    </div>
                    <div class="sub-right">
                        <a href="#"><img src="/i/cat.gif"></a>
                        שלום תותי
                    </div>
                </div>
                <div class="sub-text">
                    .זהו ביקורך ה- 18 במרכז הלמידה
                    <br/>

                    .עד כה צברת 35 שעות תרגול
                    <br/>
                    יש לך 2 הודעות חדשות בתיבת הדואר
                    <br/>
                    עד כה צברת 46 בונוסים
                    <br/><br/>
                </div>
                <div class="sub-block-border1">

                </div>
                <div class="sub-block1">

                    <div class="content-block">

                        שוחחו עם מדריך אונליין
                    </div>
                    <div class="sub-sub-block1">
                        <div class="header">
                        </div>
                        <div class="content">

                        </div>

                        <div class="footer">
                        </div>

                    </div>
                </div>

                <div class="sub-block-border2">

                </div>
                <div class="sub-block2">

                    <div class="sub-sub-block2">
                    </div>
                    <div class="content-block">
                        <div class="sub-header">
                            משוב על התרגול
                        </div>
                        <br/>
                        <strong>האם חווית שיפור או הקלה</strong><br/>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <strong>האם התרגול היה:</strong><br/>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>

                        <div class="radio_new"></div>
                        <div class="radio_text">Test</div>


                    </div>

                </div>
                <div class="sub-block-border3">
                    <div class="sub-top">
                        <div class="sub-top-content">

                            ?האם חווית בעיה בתרגול
                            <br/> <textarea class="sub_textarea"></textarea><br/>
                            האם יש לך הצעות לשיפור
                            <br/>

                            <input type="text" class="sub_text_input" value="" text="" name="">
                        </div>
                    </div>
                    <div class="sub-bottom">

                        <input type="button" class="sub_button_input" value="שלחו" text="" name="">
                    </div>
                    <div class="sub-bottom-border" id="sub-bottom-border">

                        <div class="sub-bottom-border-block">
                            <div class="sub-bottom-top"></div>
                            <div class="sub-bottom-body">

                                <div class="sub-bot-content">

                                    <strong>מאמר השבוע</strong><br><br>
                                    “על הקשר בין נחיריים לאישיות” <br>
                                    לקריאת המאמר <br><br>
                                    <strong>מונח השבוע</strong><br><br>
                                    <a href="/">טאפאס - חום . קיראו עוד</a>
                                </div>


                            </div>
                            <div class="sub-bottom-bottom"></div>
                        </div>

                        <div class="sub-view-image">
                        <div class="input-title">
                            להצטרפות לקורס הכניסו אימייל
                        </div>
                            <input type="text" class="" value="" text="" name="">

                        </div>

                        <div class="bottom-shape"><div class="text-bottom-shape">
שלחו >
                            </div></div>

<div class="bottom-shape-like"></div>

                    </div>
                </div>


            </div>


            <div class="form_wrap">


                <video id="vid1" width="689" height="579"
                       poster="http://cdn.kaltura.org/apis/html5lib/kplayer-examples/media/bbb480.jpg"
                       durationHint="33"
                        >
                    <source src="http://cdn.kaltura.org/apis/html5lib/kplayer-examples/media/bbb_trailer_400p.ogv"
                            type="video/ogg"/>
                </video>

                <div class="mail-content-wrap">

                    <div class="mail-block-title">

הודעות ממרכז הלמידה
                    </div>
                    <div class="mail-block">

                        <div class="mail-top">

                        </div>

                        <div class="mail-bottom">
                            <div class="mail-bottom-header">

                            </div>

                            <div class="mail-message">

                            </div>


                        </div>
                    </div>




                </div>



                <div class='video_link'>
                    <iframe title="YouTube video player" width="623" height="686"
                            src="http://www.youtube.com/embed/ew9KuRkTt_Y" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
                 <div class="for_ie">

                </div>

        </div>
        <header class="header">
            <a class="logo" href="" title="אימות סיסמא">אימות סיסמא</a>
            <nav>
                <ul class="nav">
                    <li><a href="index.html" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>

                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                </ul>
            </nav>
            <ul class="something">

                <li><a href="" title="הרשמה">הרשמה</a></li>
                <li><a href="" title="הרשמה">הרשמה</a></li>
                <li><a href="" title="הרשמה">הרשמה</a></li>
            </ul>
            <form class="search" action="#">
                <label for="search">הרשמה</label>
                <input type="text" name="search" id="search">

                <input type="submit" name="s_submit" id="s_submit" value="go">
            </form>
            <ul class="something2">
                <li><a href="" title="שכחתי סיסמא">שכחתי סיסמא</a></li>
                <li><a href="" title="התנתק">התנתק</a></li>
                <li><a href="" title="כניסה למערכת">כניסה למערכת</a></li>
            </ul>

        </header>
        <footer class="footer">
            <div class="text1">
                טיפולית אונליין / תקנון / כל הזכויות שמורות
            </div>
            <div class="text2">
                <span>ובים במיל</span>ל עדכונים ומש <a href="" title="אני רוצה לקב">אני רוצה לקב</a>
            </div>

        </footer>
    </section>
</div>
</body>
</html>