<div class="mail-content-wrap">
<center>
<h2>Chatting with the teacher</h2>
</center>
<div class="mail-block" style="background-color: white">
﻿<div id="chat" person="student" personid="<?php echo $this->stid ?>" otherpersonid="1"></div>
<div id="chatbox"></div>
</div><br/>
    <input type="text" id="chatinput" onkeypress="handleKeyPress(event)"/><br/>
<input type="button" id="chatsubmit" value="Say"/>
</div>