<div class="form_wrap">
                    
			<ul class="form_big">
                          <li style="width:150px;padding-right: 40px">
          <?php if (!isset ($this->data['u_picture'])): ?>
                 <a href="#"><img src="/i/noava.gif"></a>
          <?php else: ?>
                 <a href="#"><img src="<?php echo "/avatars/".$this->data['u_picture']?>"></a>
          <?php endif ?>
    
                  <input type="button" id="uploadavatar" value="Avatar"/>
                  <div id="uploadavatarform">
                      <?php
                        echo $this->uploadavatarform;
                      ?>
                  </div>
					</li>
                                        <li class="form_big" >
                                            Last payment<br/>
                                            Last payment date<br/>
      <a href="#"><img src="/i/r_button.png"></a>
                                        </li>
					<li  class="form_big">
                                        <form action="<?php echo $this->form->action ?>" method="post">
                                                        <b><?php echo $this->studentstatus ?> account</b> .................................. <b>ID: <?php echo $this->data['u_id']?></b> ...................................... <b><?php echo $this->data['u_name']?></b><br/><br/>
                                                        <div style="color:darkred">some other text goes here........................................................text.................</div><br/>
                                                        External E-mails?<?php echo $this->form->external ?>
                                                        
                                                        <div style="float:right;">
                                                            <a href="/student/profile/my-profile/"><input type="button" id="Activte_6D" value="Back"></a>
							<input type="submit" id="Pause_6D" name="save" value="Save">
                                                        </div>
					</li>

				</ul>
				<div class="form">
					<ul class="form_list">
						<li>
							<?php echo $this->form->firstname ?>
							<label for="name">שם פרטי:</label>
						</li>
						<li>
							<?php echo $this->form->lastname ?>
							<label for="lname">שם משפחה:</label>
						</li>
						<li>
							<label class="birth">שנת לידה:
                                                        <?php echo $this->form->datepicker ?>
							</label>
							<label for="sex">מין:</label>
                                                        <?php echo $this->form->sex ?>
						</li>

						<li>
							<label for="height">גובה:</label>
                                                        <?php echo $this->form->heigth ?>
							<label for="weight">משקל:</label>
                                                        <?php echo $this->form->weight ?>
						</li>
						<li>
							<?php echo $this->form->email ?>

							<label for="email">אימייל:</label>
						</li>
						<li>
							<?php echo $this->form->password1 ?>
							<label for="pass">סיסמא</label>
						</li>
						<li>
							<?php echo $this->form->password2 ?>

							<label for="c_pass">אימות סיסמא</label>
						</li>
						<li>
							<label for="state">מדינה:</label>
							<?php echo $this->form->state ?>

						</li>
						<li>
							<?php echo $this->form->address ?>
							<label for="full_adr">כתובת מלאה:</label>
						</li>
						<li>
							<p><strong>לנשים:</strong> האם את בהריון?</p>
                                                        <?php echo $this->form->pregnant ?>
						</li>

						<li>
							<label for="hz1">מספר חודשים שעברו מהלידה האחרונה: </label>
                                                        <?php echo $this->form->pregnantsince ?>
						</li>
						<li class="other_stile">
							<label for="obj">מהן המטרות שלך בתרגול איתנו?</label>
                                                        <?php echo $this->form->objectives ?>
						</li>
					</ul>
				</div>

				<div class="form">
					<h2>סמנו אם הינכם סובלים מ:</h2>
					<ul class="form_list">

						<li>
							<label for="f_15">
								<?php echo $this->form->heartpressure ?>
								מחלת לב/ עורקים/ לחץ דם גבוה
							</label>
						</li>
						<li>
							<label for="f_16">
								<?php echo $this->form->diabetes ?>

								סכרת
							</label>
						</li>
						<li>
							<label for="f_17">
								<?php echo $this->form->migrene ?>
								מיגרנה כרונית
							</label>
						</li>
						<li>

							<label for="f_18">
								<?php echo $this->form->babies ?>
								בעיות פיריון
							</label>
						</li>
						<li>
							<label for="f_19">
								<?php echo $this->form->nosleep ?>
								הפרעות שינה
							</label>

						</li>
						<li>
							<label for="f_20">
								<?php echo $this->form->digestion ?>
								מעי רגיש או בעיות עיכול אחרות
							</label>
						</li>
						<li>
							<label for="f_21">

								<?php echo $this->form->menopause ?>
								תופעות גיל המעבר
							</label>
						</li>
						<li>
							<label for="f_22">
								<?php echo $this->form->sclorosies ?>
								טרשת נפוצה
							</label>
						</li>

						<li>
							<label for="f_23">
								<?php echo $this->form->epilepsy ?>
								אפילפסיה
							</label>
						</li>
						<li>
							<label for="f_24">
								<?php echo $this->form->cancer ?>

								סרטן
							</label>
						</li>
						<li>
							<label for="f_25">
								<?php echo $this->form->asthma ?>
								קוצר נשימה/ אסטמה
							</label>
						</li>
						<li>

							<label for="f_26">
								<?php echo $this->form->artritis ?>
								דלקת פרקים
							</label>
						</li>
						<li>
							<label for="f_27">
								<?php echo $this->form->hernia ?>
								הרניה (קילה)
							</label>

						</li>
						<li>
							<label for="f_28">
								<?php echo $this->form->depression ?>
								דכאון או חרדה
							</label>
						</li>
						<li>
							<label for="f_29">

								<?php echo $this->form->headaches ?>
								כאבי ראש או סחרחורות
							</label>
						</li>
						<li>
							<label for="f_30">
								<?php echo $this->form->fatigue ?>
								עייפות כרונית או פיברומיאלגיה
							</label>
						</li>

						<li>
							<label for="f_31">
								<?php echo $this->form->injury ?>
								פציעה או תאונה מהעבר
							</label>
						</li>
						<li class="textarea_field">
							<label for="f_32">הערות:</label>
							<?php echo $this->form->injurytext ?>

						</li>
						<li>
							<label for="f_33">
								<?php echo $this->form->medication ?>
								נוטלים תרופות או תוספים באופן קבוע. פירוט:
							</label>
							<?php echo $this->form->medicationtext ?>
						</li>
					</ul>

				</div>
				<div class="form">
					<h2>שאלות כלליות :</h2>
					<ul class="form_list">
						<li>
							<div class="input_wrap">
									<?php echo $this->form->walk ?>
							</div>
							<p>האם ביכולתך ללכת בעצמך?</p>


						</li>
						<li>
							<div class="input_wrap">
								<?php echo $this->form->hands ?>
							</div>
							<p>מגבלה בשימוש בידיים ?</p>


						</li>
						<li>
							<div class="input_wrap">
                                                                 <?php echo $this->form->legs ?>
							</div>
							<p>מגבלה בשימוש ברגליים?</p>


						</li>
						<li>
							<div class="input_wrap">
                                                                 <?php echo $this->form->backashes ?>
							</div>
							<p>האם סובל/ת מכאבי גב או צוואר?</p>


						</li>
						<li>
							<div class="input_wrap">
                                                                 <?php echo $this->form->disc ?>
							</div>
							<p>האם יש לך פריצת דיסק או בלט?</p>


						</li>
						<li>
							<?php echo $this->form->general1 ?>
							<label for="f_1">אם כן באיזה חוליות?</label>
						</li>
						<li>
							<?php echo $this->form->general2 ?>

							<label for="f_2">פירוט או הערות :</label>
						</li>
						<li>
							<?php echo $this->form->general3 ?>
						</li>
					</ul>
					<h2>במסגרת התרגול ארצה להתמקד בעיקר ב:</h2>
					<ul class="form_list">

						<li>
							<label for="f_4">
								<?php echo $this->form->lowerback ?>
								גב תחתון</label>

						</li>
						<li>
							<label for="f_5">
								<?php echo $this->form->upperback ?>

								גב עליון
							</label>

						</li>
						<li>
							<label for="f_6">
								<?php echo $this->form->neck ?>
								כתפיים וצוואר
							</label>

						</li>

						<li>
							<label for="f_7">
								<?php echo $this->form->feet ?>
								כפות רגליים
							</label>

						</li>
						<li>
							<label for="f_8">
								<?php echo $this->form->knees ?>

								knees
							</label>
						</li>
						<li>
							<label for="f_9">
								<?php echo $this->form->breath ?>
								breath
							</label>
						</li>
						<li>

							<label for="f_10">
								<?php echo $this->form->pelvis ?>
								כפות ידיים
							</label>
						</li>
						<li>
							<label for="f_11">
								<?php echo $this->form->wrists ?>
								מרפקים
							</label>

						</li>
						<li>
							<label for="f_12">
								<?php echo $this->form->ankles ?>
								ראש
							</label>
						</li>
						<li>
							<label for="f_13">

								<?php echo $this->form->head ?>
								מצב מנטלי/ רגשי
							</label>
						</li>
						<li class="textarea_field">
							<label for="f_14">הערות :</label>
							<?php echo $this->form->moreinfo ?>
						</li>

					</ul>
				</div>
                    </form>
	</div>
