<div class="side_block" id="chat" person="student" personid="<?php echo $this->stid ?>">
    <div class="sub">
        <div class="sub-left">
            <a href="/student/profile/upgrade-account/" target="new"><img src="/i/r_button.png"></a>
            <a href="/student/profile/my-profile-edit/">Edit Your Profile</a>
        </div>
        <div class="sub-right">
          <?php if (!isset ($this->studentMainData['u_picture'])): ?>
                 <a href="#"><img src="/i/noava.gif"></a>
          <?php else: ?>
                 <a href="#"><img src="<?php echo "/avatars/".$this->studentMainData['u_picture']?>"></a>
          <?php endif ?>
        </div>
      </div>
           <b><?php
            echo $this->studentMainData['u_name']." ".$this->studentMainData['u_family_name'];
            ?></b>
    <div class="sub-text">
        <a href="/student/profile/chat/" target="new">chat with teacher</a>
        <a href="/student/profile/chat/" target="new"><span id="chatrequest"></span></a>
        <br/>
        .זהו ביקורך ה- 18 במרכז הלמידה<?php echo $this->studentMainData['u_visits_amount'] ?>
        <br/>

        .עד כה צברת 35 שעות תרגול<div id="numberofunreadmails" q="<?php echo $this->unreadmessages ?>"><?php echo $this->unreadmessages ?></div>
        <br/>
        יש לך 2 הודעות חדשות בתיבת הדואר
        <br/>
        עד כה צברת 46 בונוסים
        <br/><br/>
    </div>
    <div class="sub-block-border1">
    </div>
    <div class="sub-block1">
        <div class="content-block">
            שוחחו עם מדריך אונליין
        </div>
        <div class="sub-sub-block1">
            <div class="header">
            </div>
            <div class="content">
            </div>
            <div class="footer">
            </div>
        </div>
    </div>
    <div class="sub-block-border2">
    </div>
    <div class="sub-block2">

        <div class="sub-sub-block2">
        </div>
        <div class="content-block">
                        <div class="sub-header">
                            משוב על התרגול
                        </div>
                        <br/>
                        <strong>האם חווית שיפור או הקלה</strong><br/>
improvements
                        <div class="radio_new"><input type="radio" name="improvement" value="Yes"/></div>
                        <div class="radio_text">Yes</div>

                        <div class="radio_new"><input type="radio" name="improvement" value="No"/></div>
                        <div class="radio_text">No</div><br/><br/>

                        <strong>האם התרגול היה:</strong><br/>

                        <div class="radio_new"><input type="radio" name="level" value="Hard"/></div>
                        <div class="radio_text">Hard</div>

                        <div class="radio_new"><input type="radio" name="level" value="Suitable"/></div>
                        <div class="radio_text">Mid</div>

                        <div class="radio_new"><input type="radio" name="level" value="Easy"/></div>
                        <div class="radio_text">Easy</div>

        </div>
    </div>
    <div class="sub-block-border3">
        <div class="sub-top">
                        <div class="sub-top-content">

                            ?האם חווית בעיה בתרגול
                            <br/> <textarea class="sub_textarea" id="difficult"></textarea><br/>
                            
                            האם יש לך הצעות לשיפור
                            <br/>

                            <input type="text" class="sub_text_input" id="suggestion" value="" text="" name="">
                        </div>
        </div>
        <div class="sub-bottom">
        <input type="button" class="sub_button_input" value="שלחו" text="" name="" id="sendfeedback" stid ="<?php echo $this->stid ?>">
      </div>
        <div class="sub-bottom-border" id="sub-bottom-border">
            <div class="sub-bottom-border-block">
                <div class="sub-bottom-top"></div>
                <div class="sub-bottom-body">
                    <div class="sub-bot-content">
                        <strong>מאמר השבוע</strong><br><br>
                        “על הקשר בין נחיריים לאישיות” <br>
                        לקריאת המאמר <br><br>
                        <strong>מונח השבוע</strong><br><br>
                        <a href="/">טאפאס - חום . קיראו עוד</a>
                    </div>
                </div>
                <div class="sub-bottom-bottom"></div>
            </div>
            <?php if (!$this->all6dvideos): ?>
            <div class="sub-view-image" id="course6d" stid ="<?php echo $this->stid ?>">
            <?php else: ?>
            <div class="sub-view-image" stid ="<?php echo $this->stid ?>">
            <?php endif; ?>
            <div class="input-title">
                להצטרפות לקורס הכניסו אימייל
            </div>

            </div>
            <div class="bottom-shape"><div class="text-bottom-shape">
שלחו >
                </div></div>
<div class="bottom-shape-like"></div>
        </div>

    </div>
</div>
 <div class="form_wrap">
<?php if ($this->status6d==1): ?>
      <div id="videoDivInfo" video="<?php echo $this->all6dvideos[0]['v6ds_id'] ?>" course6d="1"></div>
      <div id="vid1">
       <?php echo $this->all6dvideos[0]['v6d_code'] ?>
     </div>
<?php else:?>
<?php if (!$this->kaltura): ?>
      <div id="vid1">
       <script type="text/javascript" src="http://content.bitsontherun.com/players/WGdA3yA2-TPLLuQfB.js"></script>
     </div>
     <?php else: ?>
      <div id="videoDivInfo" video="<?php echo $this->kaltura['vam_id'] ?>" course6d="0"></div>
      <div id="vid1" video="<?php echo $this->kaltura['vam_video_player1'] ?>">
        <script type="text/javascript" src="http://content.bitsontherun.com/players/<?php echo $this->kaltura['vam_video_player1'] ?>-TPLLuQfB.js"></script>
     </div>
     <?php endif;?>
<?php endif; ?>
    <div class="mail-content-wrap">
        <div class="mail-block-title">
הודעות ממרכז הלמידה
        </div>
        <div class="mail-block">
            <table id="mailtable">
                <th>From</th><th>Subject</th><th>Date</th><th></th>
                <?php if ($this->mails): ?>
                <?php foreach($this->mails as $mail): ?>
                <tr class="eachmessage" id="<?php echo $mail['spm_id'] ?> " side="student">
                    <td width="20%" <?php echo ($mail['spm_from_teacher_id']&&!$mail['spm_is_new']? "class='unread'": ""); ?>><?php echo $this->teacher ?></td>
                    <td width="50%" <?php echo ($mail['spm_from_teacher_id']&&!$mail['spm_is_new']? "class='unread'": ""); ?>><?php echo $mail['spm_subject'] ?></td>
                    <td width="25%" <?php echo ($mail['spm_from_teacher_id']&&!$mail['spm_is_new']? "class='unread'": ""); ?>><?php echo $mail['spm_datetime'] ?></td>
                    <td width="5%">
                        <?php if ($mail['spm_from_teacher_id']): ?>
                        <img src="/i/mail_in.png" title="inbox" />
                        <?php else: ?>
                        <img src="/i/mail_out.png" title="outbox"/>
                        <?php endif;?>
                    </td>
                </tr>
                <tr>
                    <td class="mailbody" colspan="4">
                        <?php echo $mail['spm_body'] ?><br/>
                        <?php if ($mail['spm_from_teacher_id']): ?>
                        <div class="replylink"
                           id="<?php echo $mail['spm_id']?>"
                           subj="<?php echo $mail['spm_subject'] ?>">reply</div>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
                           <tr class="eachmessage">
                    <td></td><td></td><td></td><td></td>
                </tr>
                <?php else :?>
                <tr><td colspan="4"><i>אין לך עדיין הודעות ממרכז הלמידה</i></td></tr>
              <?php endif;?>
        </table><br/>
            <img id="newmaillink" src="/i/email.png" title="write new mail"/>
                        <span id="newmailform">
                            <form method="post" action="/student/profile/my-profile/">
                            subject <input type="text" name="subject" id="mailsubj" /><br/><br/>
                            <textarea name="mailbody" id="mailbody" cols="30" rows="5"></textarea>
                            <br/><input type="submit" name="mailsend" id="mailsend" value="send"/>
                            </form>
                        </span>
        </div>
    </div>
    <div class='video_link' id="youtube">
            <?php if ($this->youtube):?>
                <?php echo $this->youtube['vam_video_player2'] ?>
            <?php else :?>
                    <iframe title="YouTube video player" width="623" height="686"
                    src="http://www.youtube.com/embed/BjfCfIPP8ps" frameborder="0" allowfullscreen></iframe>
            <?php endif; ?>
    </div>
</div>
     <div class="for_ie">
    </div>
