<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
	<title>אימות סיסמא</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
	<!--[if gt IE 7]><!-->
	<link rel="stylesheet" media="screen" type="text/css" href="/styles/main.css">
	<!--<![endif]-->
	<!--[if lt IE 9]>
	<script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!--[if lt IE 8]>
	<link rel=stylesheet media="screen" type="text/css" href="/styles/ie.css" />
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script type="text/javascript" src="/js/ie.js"></script>
	<![endif]-->
        <link rel="stylesheet" href="/styles/datepicker/jquery.ui.all.css"/>
        <link rel="stylesheet" href="/styles/datepicker/jquery-ui.css"/>
        <script type="text/javascript"  src="/js/jquery-1.4.4.js"></script>
        <script type="text/javascript"  src="/js/jquery.ui.core.js"></script>
        <script type="text/javascript"  src="/js/jquery.ui.widget.js"></script>
        <script type="text/javascript"  src="/js/jquery.ui.datepicker.js"></script>
        <script type="text/javascript"  src="/js/tipulitonline.js"></script>
        <script type="text/javascript"  src="/js/jquery-ui.min.js"></script>


<?php echo $this->headScript(); ?>
<?php echo $this->headLink(); ?>
</head>
<body class="main_page">

<?php echo $this->layout()->content ?>
   
</body>
</html>