<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
	<title>אימות סיסמא</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
	<!--[if gt IE 7]><!-->
	<link rel="stylesheet" media="screen" type="text/css" href="/styles/main.css">
	<!--<![endif]-->
	<!--[if lt IE 9]>
	<script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!--[if lt IE 8]>
	<link rel=stylesheet media="screen" type="text/css" href="/styles/ie.css" />
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script type="text/javascript" src="/js/ie.js"></script>
	<![endif]-->
        <link rel="stylesheet" href="/styles/datepicker/jquery.ui.all.css"/>
        <link rel="stylesheet" href="/styles/datepicker/jquery-ui.css"/>
        <script type="text/javascript"  src="/js/jquery-1.4.4.js"></script>
        <script type="text/javascript"  src="/js/jquery.ui.core.js"></script>
        <script type="text/javascript"  src="/js/jquery.ui.widget.js"></script>
        <script type="text/javascript"  src="/js/jquery.ui.datepicker.js"></script>
        <script type="text/javascript"  src="/js/tipulitonline.js"></script>
        <script type="text/javascript"  src="/js/jquery-ui.min.js"></script>


<?php echo $this->headScript(); ?>
<?php echo $this->headLink(); ?>
</head>
<body class="main_page">
<div class="wrapper">
	<section class="base">
		<div class="content_row">
			<header>
				<h1 class="headline">הרשמה</h1>
			</header>

			<div class="side_block">
				<img src="/i/img.jpg" alt=""/>
			</div>
<?php echo $this->layout()->content ?>
</div>
		<header class="header">
			<a class="logo" href="" title="אימות סיסמא">אימות סיסמא</a>
			<nav>
				<ul class="nav">

					<li><a href="index.html" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>

				</ul>
			</nav>
			<ul class="something">
				<li><a href="" title="הרשמה">הרשמה</a></li>
				<li><a href="" title="הרשמה">הרשמה</a></li>
				<li><a href="" title="הרשמה">הרשמה</a></li>
			</ul>

				<form class="search" action="">
					<label for="search">הרשמה</label>
					<input type="text" name="search" id="search">
					<input type="submit" name="s_submit" id="s_submit" value="go">
				</form>
			<ul class="something2">
				<li><a href="#" check='0' id='showloginform' title="הרשמה">Login</a></li>
				<li><a href="" title="הרשמה">הרשמה</a></li>

			</ul>
		</header>
		<footer class="footer">
			<div class="text1">
				טיפולית אונליין / תקנון / כל הזכויות שמורות
			</div>
			<div class="text2">
				<span>ובים במיל</span>ל עדכונים ומש <a href="" title="אני רוצה לקב">אני רוצה לקב</a>

			</div>
		</footer>
	</section>
</div>
</body>
</html>