<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>National Safety Compliance, INC</title>
    <link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">
    <script type="text/javascript"  src="/scripts/jquery-1.4.4.js"></script>
    <script type="text/javascript"  src="/scripts/jquery.ui.core.js"></script>
    <script type="text/javascript"  src="/scripts/jquery.ui.widget.js"></script>
    <script type="text/javascript"  src="/scripts/jquery.ui.datepicker.js"></script>
    <script type="text/javascript"  src="/scripts/tipulitonline.js"></script>

<?php echo $this->headScript(); ?>
<?php echo $this->headLink(); ?>
    
</head>
<body>

        <?php echo $this->layout()->content ?>

</body>
</html>

