<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <title>אימות סיסמא</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
    <!--[if gt IE 7]><!-->
    <link rel="stylesheet" media="screen" type="text/css" href="/styles/main_std.css">

    <!--<![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if IE 7]>
    <link rel="stylesheet" media="screen" type="text/css" href="/styles/cross/ie7.css">
    <![endif]-->
    <!--[if lt IE 8]>
    <link rel=stylesheet media="screen" type="text/css" href="/styles/ie.css"/>

    <script type="text/javascript" src="/js/ie.js"></script>
    <![endif]-->

     <!--[if IE]>
        <link rel=stylesheet media="screen" type="text/css" href="/styles/cross/ie.css"/>
    <![endif]-->

    <!--[if opera 11]>
    <link rel=stylesheet media="screen" type="text/css" href="/styles/cross/op.css"/>
    <![endif]-->

    <script type="text/javascript" src="/js/kultura/jquery-1.4.2.min.js"></script>

    <!-- Include Kultura -->
    <!-- Debug version: If using the debug version you can remove all the below js / css references -->
    <!--  <script type="text/javascript" src="/js/kultura/mwEmbed.js" ></script>  -->

    <style type="text/css">
        @import url("/js/kultura/skins/jquery.ui.themes/kaltura-dark/jquery-ui-1.7.2.css");
    </style>
    <style type="text/css">
        @import url("/js/kultura/mwEmbed-player-static.css");
    </style>
    <script type="text/javascript" src="/js/kultura/mwEmbed-player-static.js"></script>
    <script type="text/javascript" src="/js/mailexchange.js"></script>
    <script type="text/javascript" src="/js/video.js"></script>
    <script type="text/javascript" src="/js/swfobject.js"></script>
    <script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
    <script type="text/javascript">
    bkLib.onDomLoaded(function() {
	new nicEditor().panelInstance('mailbody');
    });
    </script>
    <script>
        function onYouTubePlayerReady(id) {
        alert("FFF");
      }
    </script>
</head>
<body class="main_page">
<div class="wrapper">
    <section class="base">
        <div class="content_row">
            <?php echo $this->layout()->content ?>
            <!--<header>
                   <h1 class="headline">הרשמה</h1>
               </header>-->
        </div>
        <header class="header">
            <a class="logo" href="" title="אימות סיסמא">אימות סיסמא</a>
            <nav>
                <ul class="nav">
                    <li><a href="index.html" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>

                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                    <li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
                </ul>
            </nav>
            <ul class="something">

                <li><a href="" title="הרשמה">הרשמה</a></li>
                <li><a href="" title="הרשמה">הרשמה</a></li>
                <li><a href="" title="הרשמה">הרשמה</a></li>
            </ul>
            <form class="search" action="#">
                <label for="search">הרשמה</label>
                <input type="text" name="search" id="search">

                <input type="submit" name="s_submit" id="s_submit" value="go">
            </form>
            <ul class="something2">
                <li><a href="" title="שכחתי סיסמא">שכחתי סיסמא</a></li>
                <li><a href="" title="התנתק">התנתק</a></li>
                <li><a href="" title="כניסה למערכת">כניסה למערכת</a></li>
            </ul>

        </header>
        <footer class="footer">
            <div class="text1">
                טיפולית אונליין / תקנון / כל הזכויות שמורות
            </div>
            <div class="text2">
                <span>ובים במיל</span>ל עדכונים ומש <a href="" title="אני רוצה לקב">אני רוצה לקב</a>
            </div>

        </footer>
    </section>
</div>
</body>
</html>