<div class="wrapper">
	<section class="base">
		<div class="content_row">
			<header>
				<h1 class="headline">הרשמה</h1>
			</header>

			<div class="side_block">
				<img src="/i/img.jpg" alt=""/>
			</div>
                        <div class="form_wrap">
                            <div class="form">
                                  <ul class="form_list">
                                    <?php
                                           echo $this->form;
                                    ?>
                                </ul>
                            </div>
                        </div>
		</div>
		<header class="header">
			<a class="logo" href="" title="אימות סיסמא">אימות סיסמא</a>
			<nav>
				<ul class="nav">

					<li><a href="index.html" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>
					<li><a href="" title="אימות סיסמא">אימות סיסמא</a></li>

				</ul>
			</nav>
			<ul class="something">
				<li><a href="" title="הרשמה">הרשמה</a></li>
				<li><a href="" title="הרשמה">הרשמה</a></li>
				<li><a href="" title="הרשמה">הרשמה</a></li>
			</ul>

				<form class="search" action="">
					<label for="search">הרשמה</label>
					<input type="text" name="search" id="search">
					<input type="submit" name="s_submit" id="s_submit" value="go">
				</form>
			<ul class="something2">
				<li><a href="#" check='0' id='showloginform' title="הרשמה">Login</a></li>
				<li><a href="" title="הרשמה">הרשמה</a></li>

			</ul>
		</header>
		<footer class="footer">
			<div class="text1">
				טיפולית אונליין / תקנון / כל הזכויות שמורות
			</div>
			<div class="text2">
				<span>ובים במיל</span>ל עדכונים ומש <a href="" title="אני רוצה לקב">אני רוצה לקב</a>

			</div>
		</footer>
	</section>
</div>